import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ToggleMode/context/Theme";
import NavBar from "@/components/navBar/NavBar";
import Headr from "@/components/navBar/Headr";
import UserProvider from "@/components/login&signUp/context/user";
import ScrollToTopButton from "@/components/scrollToTop/ScrollToTopBtn";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Eco Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className && ""} >
        <ThemeProvider>
          <UserProvider>
            {children}
            <ScrollToTopButton />
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
